# Generated by Django 3.2.9 on 2021-12-05 10:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='featureArray',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[1, 2, 3, 4, 5, 6, 7, 8], size=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='firebaseID',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
