# Generated by Django 3.2.9 on 2021-12-07 09:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211205_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='featureArray',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), max_length=8, size=None),
        ),
    ]
